### PR TITLE
feat/add_tracking

### LINKED ISSUE #55: Add rudimentary tracking
Add a call to a Lambda function or other way to track usage of the tutorial

### PR DESCRIPTION
**Pull request by agardnerIT**
Resolves #55 

Signed-off-by: adamgardnerit <adam@agardner.net>

### CODE REVIEW

**Review by afzal442 — COMMENTED** [review]
This is great though. Any UI view would be great. Could you post a screen shot of what or how we get? Thanks 😄

**Review by afzal442 — APPROVED** [review]
LGTM!

**Comment by agardnerIT** [comment]
image

**Comment by afzal442** [comment]
@agardnerIT Thanks much, that is exactly I wanted to take a glance on that. You are doing amazing work. 🛩️

**Pull request merged**
